<a href="https://colab.research.google.com/github/rganesh203/PythonNumpy/blob/main/Best_numpy_functions_for_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center> <img src='https://miro.medium.com/max/765/1*cyXCE-JcBelTyrK-58w6_Q.png'/></center>
<center><h2>Best Numpy Functions For Data Science </h2></center>

Numpy stands for numerical python and is a library in python that adds the functionality of large multi-dimensional arrays and matrices. It works as a building block for all the libraries in pydata ecosystem. Numpy is one of the most useful tools for a data scientist that uses python. It can handle large-size data efficiently. One of the biggest reasons to use NumPy is its arrays and multiple scientific functions to work with arrays.

###==========**Numpy**==========
    1. numerical python
    2. provide lot of functions to work in adomain & linear algebra, FT and Matrices.
    3. provide functions related to arrays
    4. create an array called ndarray.
    5. working of ndarray is faster than lists
    6. get the version
        print(numpy.__version__)
    7. Most of the part of Numpy --------C & C++.

#### **========𝗧𝗔𝗕𝗟𝗘 𝗢𝗙 𝗖𝗢𝗡𝗧𝗘𝗡𝗧========**
- Array Creation Methods
- Array Operations
- Replacing Values Inside Array
- Set Operations
- Splitting
- Stacking
- Comparing Two Arrays
- Repeating Array Elements
- Einstein Summation Conventions
- Statistical Analysis
- Array Printing Options
- Save and Load Array Data

<h2 id='createarray'>Array Creation Methods</h2>

# Array dimensions
    0-D array
    1-D array
    2-D array
    3-D array
    ----etc.

#Arrays with Existing Data
    ASARRAY( ),
    FROMBUFFER( ),
    FROMITER( ) IN NUMPY

### Array
It is used to create one-dimensional or multidimensional arrays from scratch.
![image.png](attachment:5d9e81cc-5933-4e43-9096-56246ce548a0.png)

▪▶**Important params**<br>
`dtype`: desired data type for the resultant array.<br>
`ndim`: Specify the minimum number of dimensions for the resultant array.

In [ ]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

You can also use this function to convert series or dataframes into a NumPy array.

In [ ]:
import pandas as pd
sex = pd.Series(['Male','Male','Female'])
np.array(sex)

array(['Male', 'Male', 'Female'], dtype=object)

### Linspace
Creates an array with evenly spaced float numbers over a specified interval.
![image.png](attachment:3c46f8c9-1162-47d6-9eef-f75779931b73.png)
**▪▶ Important params**<br>
`start`: starting index<br>
`end`: last index<br>
`num`: number of samples to generate, default = 50.

In [ ]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

###Arange
Return evenly spaced integer values over a given interval with some step size.
![image.png](attachment:5beaf627-a740-46b4-9077-a400c26c2a6a.png)

**▪▶Important params**<br>
`step`: Space between values.

In [ ]:
np.arange(5,10,2)

array([5, 7, 9])

### Uniform Samples
Generate a random sample from a uniform distribution between lower and higher limit values.
![1_zhQK7mUMgKakLHOXre1d3Q.png](attachment:427153ea-a92f-49df-a379-48545f25d604.png)

In [ ]:
np.random.uniform(5,10,size = 4)

array([7.72487975, 8.91942166, 5.53872263, 6.54556745])

In [ ]:
np.random.uniform(size = 5)

array([0.64006641, 0.36551985, 0.54317884, 0.16198007, 0.16498553])

In [ ]:
np.random.uniform(size = (2,3))

array([[0.43680957, 0.37239784, 0.65596076],
       [0.17796214, 0.06426845, 0.67394871]])

### Random.randint
rand()
randn()
ranf()
randint()
Generate n random integer samples within a range.
![1_VvCmQnn8u_OyIixZfkyZbw.png](attachment:51b49e32-2fe3-4d07-b218-ade8d73c7244.png)

In [ ]:
np.random.randint(5,10,10)

array([5, 5, 9, 6, 5, 9, 6, 7, 5, 8])

### 6. Random.random
Generate n random float samples.![1_FPvTLpPERIOAEGSTRdBPAw.png](attachment:3030a88f-9347-400a-a81e-142aa5ebab18.png)

In [ ]:
np.random.random(3)

array([0.04782005, 0.38949813, 0.22376968])

### 7. Logspace
Generate evenly spaced numbers on a log scale.![1_k6E0IikIX7zTmyPGZy29Eg.png](attachment:b487115a-01aa-4d64-bb87-af104ae4a221.png)

**▪▶ Important params**<br>
`start`: starting value of the sequence.<br>
`end`: last value of the sequence.<br>
`endpoint`: if True, the last sample will be included in the sequence.<br>
`base`: The base of the log space. default is 10.

In [ ]:
np.logspace(0,10,5,base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

### 8. Array of zero
np.zeroes function helps to create an array of 0.![1_Hj1ne3gg2wwJ5JQKWx12Jw.png](attachment:fabb507b-f3a1-4c04-bb50-069b5c9f2c65.png)
**▪▶ Important params**<br>
`shape`: shape of the resultant array.<br>
`dtype`: desired data type of resultant array. ‘int’ or default ‘float’

In [ ]:
np.zeros((2,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### 9. Array of Ones
np.ones function helps to create an array of 1.![1_d9VMSaNyH-RMV6sFK_09tQ.png](attachment:df5f7950-3691-4244-8ee1-0f81a76bead4.png)

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 10. Array of k Random Value
Creates an n-dimensional array of a random value.![1_dTZrwbRMeMKcekl9ZXsCAw.png](attachment:5a415716-49b1-4b74-a83f-4a688ba3b8da.png)
**▪▶ Important params**<br>
`fill_value`: Random value to fill inside the array.

In [ ]:
np.full((2,4),fill_value=2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

## Array Operations

### 12. Min
Return the minimum value from the array.![1_Iah738_7UqXwT9JBE4tcDw.png](attachment:aa59ef40-ad61-45bd-bda5-0cefd119b849.png)

**▪▶ Important params**<br>
`axis`: axis along which to operate.<br>
`out`: alternative array to store the output.

In [ ]:
arr = np.array([1,1,2,3,3,4,5,6,6,2])
np.min(arr)

1

### 13. Max
Return the maximum value from the array.![1_03Nd6aG5QAGXMnTniEWbEw.png](attachment:b7d15408-8edb-4b01-97ba-4a4256788eef.png)

In [ ]:
np.max(arr)

6

### 14. Unique
Return an array with all the unique elements sorted.
![1_j_bhHwxowLqPxbAl2XbTmg.png](attachment:5303cd5a-dbc2-426a-9ff6-0afc72fe5260.png)

**▪▶ Important params**<br>
`return_index`: if True, return the indices of the array.<br>
`return_inverse`: if True, return the indices of the unique array.<br>
`return_counts`: if True, return the number of times each unique element appears inside the array.<br>
`axis`: The axis to operate on. By default, the array is considered flattened.

In [ ]:
np.unique(arr,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 2, 1, 1, 2]))

### 15. Mean
It is used to get the mean of the array.![1_uotYccJmQ5uxlFk1yv7HhA.png](attachment:14285ad7-296e-46be-9ec9-c1a803e796b8.png)

In [ ]:
np.mean(arr,dtype='int')

3

### 16. Median
Return the median value of the array.![1_sSs_cxxBBgUlHGQ2IGoboA.png](attachment:d8784034-2618-408c-84ab-a9dc96b08520.png)

In [ ]:
arr = np.array([[1,2,3],[5,8,4]])
np.median(arr)

3.5

### 17. Digitize
Return the indices of the bins to which each value in the input array belongs.![1_WsF4aLzDyYQ4rSraviyMaw.png](attachment:e7f22293-53cb-470a-b09c-e9d7640e6ca9.png)
**▪▶ Important params**<br>
`bins`: Array of bins.<br>
`right`: Indicates whether the interval includes the right or left bin edge.

In [ ]:
a = np.array([-0.9, 0.5, 0.9, 1, 1.2, 1.4, 3.6, 4.7, 5.3])
bins = np.array([0,1,2,3])
np.digitize(a,bins)

array([0, 1, 1, 2, 2, 2, 4, 4, 4])

```
Exp        Value
x < 0     :   0
0 <= x <1 :   1
1 <= x <2 :   2
2 <= x <3 :   3
3 <=x     :   4
Compares -0.9 to 0, here x < 0 so Put 0 in resulting array.
Compares  0.5 to 0, here 0 <= x <1 so Put 1.
.
Compares 5.4 to 4, here 3<=x so Put 4
```

### 18. Reshape
It is one of the most used functions of NumPy. It Returns an array containing the same data with a new shape.![1_sg0TYQZzWYZiTzTpUKC7Og.png](attachment:c9c09732-80c1-461c-baa8-7fb7cd2bc3ae.png)

In [ ]:
A = np.random.randint(15,size=(4,3))
A

array([[ 3,  3, 13],
       [ 3,  8,  1],
       [ 4,  2,  6],
       [14,  9,  8]])

In [ ]:
A.reshape(3,4)

array([[ 3,  3, 13,  3],
       [ 8,  1,  4,  2],
       [ 6, 14,  9,  8]])

In [ ]:
A.reshape(-1)

array([ 3,  3, 13,  3,  8,  1,  4,  2,  6, 14,  9,  8])

### 19. Expand Dimensions
It is used to expand the dimensions of an array. This method is useful for creating sample test data for testing a machine learning model.![1_LTIcxoFlpg-zN87ma4yi8g.png](attachment:8af049c7-9393-4f91-b0aa-98b3bb5a39ff.png)

In [ ]:
arr = np.array([ 8, 14,  1,  8, 11,  4,  9,  4, 1, 13, 13, 11])
np.expand_dims(arr,axis=0)

array([[ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11]])

In [ ]:
np.expand_dims(arr,axis=1)

array([[ 8],
       [14],
       [ 1],
       [ 8],
       [11],
       [ 4],
       [ 9],
       [ 4],
       [ 1],
       [13],
       [13],
       [11]])

## 20. Squeeze
Reduce the dimension of an array by removing single-dimensional entrie![1_lFO6q9flt0_bqO_e2oRfWA.png](attachment:ab4bbf86-8472-428a-afbe-d2054e6dbf40.png)

In [ ]:
arr = np.array([[ 8],[14],[ 1],[ 8],[11],[ 4],[ 9],[ 4],[ 1],[13],[13],[11]])
np.squeeze(arr)

array([ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11])

### 21. Count Non-Zero
Count all the non-zero elements and return their count.![1_jxsYNB6uHpjMynqgZ1_PFw.png](attachment:af19eaeb-8cd1-483a-97d3-7df03dc10ac5.png)

In [ ]:
a = np.array([0,0,1,1,1,0])
np.count_nonzero(a)

3

### 22. argwhere
Find and return all the indices of non-zero elements.![1__oc7SUrWanmeNPFKAOedpw.png](attachment:d01111e5-2d51-4537-b9c0-fe74fe015ee8.png)

In [ ]:
a = np.array([0,0,1,1,1,0])
np.argwhere(a)

array([[2],
       [3],
       [4]])

### 23. argmax & argmin
argmax returns the index of the max element from the array. It can be used to get the index of high probability predicted labels in multiclass image classification problems.![1_iHMw3cYjD64NiNQwO7vikQ.png](attachment:ce514e26-6810-443a-a574-a486ec01c48c.png)

In [ ]:
arr = np.array([[0.12,0.64,0.19,0.05]])
np.argmax(arr)

1

argmin will return the index of the lowest element from the array.
![1_f5eRCZFBcmKjfAyWhxbhQQ.png](attachment:59b107a2-e041-4846-89e5-e33cc2f4cfa4.png)

In [ ]:
np.argmin(min)

0

### 24. Sort
Sort the array and return.![1_P9UmfhqI95AbeWzFKr55Ew.png](attachment:d330b6f0-fa6d-4577-a5a9-3a34f5baf0df.png)

**▪▶ Important params**<br>
`kind`: Sorting algorithm to use. {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}

In [ ]:
arr = np.array([2,3,1,7,4,5])
np.sort(arr)

array([1, 2, 3, 4, 5, 7])

### 25. Abs
Return the absolute values of elements inside an array. It is useful when an array contains negative values.

In [ ]:
A = np.array([[1,-3,4],[-2,-4,3]])
np.abs(A)

array([[1, 3, 4],
       [2, 4, 3]])

### 26. Round
Round the float values to a specified number of decimal points.![1_tzU3BQvlByNniXqvhMJO3A.png](attachment:087aae8a-6caf-4477-a48a-ef4924809037.png)

**▪▶ Important params**<br>
`decimals`: Number of decimals point to keep.

In [ ]:
a = np.random.random(size=(3,4))
a

array([[0.04005144, 0.87084966, 0.08178962, 0.28253708],
       [0.85762161, 0.77021164, 0.72939886, 0.65406504],
       [0.53958055, 0.21585068, 0.82823812, 0.51499837]])

In [ ]:
np.round(a,decimals=0)

array([[0., 1., 0., 0.],
       [1., 1., 1., 1.],
       [1., 0., 1., 1.]])

In [ ]:
np.round(a,decimals=1)

array([[0. , 0.9, 0.1, 0.3],
       [0.9, 0.8, 0.7, 0.7],
       [0.5, 0.2, 0.8, 0.5]])

### 27. Clip
It is used to keep the values of an array within a range.

In [ ]:
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

In [ ]:
arr.clip(0,3)

array([0, 1, 0, 0, 3, 3, 3, 2, 3])

In [ ]:
arr.clip(3,5)

array([3, 3, 3, 3, 5, 5, 5, 3, 3])

***

## Replacing Values Inside Array

### 28. Where
Return elements from an array where a condition satisfies.![1_9-_yZurf1saGMDbNptiLZQ.png](attachment:a7f3ced8-4834-4eca-ace4-82c5bf940c99.png)

**▪▶ Important params**
`condition`: condition to match. if true yield xotherwise y.

In [ ]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.where(a>5)

(array([2, 2, 2, 3, 3, 3]), array([0, 1, 2, 0, 1, 2]))

```
'''
[2][0] ᴇʟᴇᴍᴇɴᴛ (2ɴꜱ ʀᴏᴡ 0ᴛʜ ᴄᴏʟᴜᴍɴ) 6 > 5, ʀᴇᴛᴜʀɴ
[2][1] ᴇʟᴇᴍᴇɴᴛ (2ɴᴅ ʀᴏᴡ 1ꜱᴛ ᴄᴏʟᴜᴍɴ) 7 > 5, ʀᴇᴛᴜʀɴ
.
[3][2] ᴇʟᴇᴍᴇɴᴛ (3ᴅ ʀᴏᴡ 2ɴᴅ ᴄᴏʟᴜᴍɴ) 11 > 5, ʀᴇᴛᴜʀɴ
'''
```

In [ ]:
a[np.where(a>5)]

array([ 6,  7,  8,  9, 10, 11])

It can also be used to replace elements inside the panda’s data frame.

`np.where(data[feature].isnull(), 1, 0)`

```
Replace Null Values with 1 and other as 0
```


### 29. Put
Replaces specified elements of an array with given values.![1_OWHgR8R6ilotQl9F-r-EFw.png](attachment:e905955a-3cc6-486b-be7e-88119def51d5.png)

**▪▶ Important params**<br>
`a`: array<br>
`ind`: indices to be replaced.<br>
`v`: values to place.

In [ ]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.put(arr,[1,2],[6,7])
arr

array([1, 6, 7, 4, 5, 6])

### 30. Copyto
Copy the content of one array into another.![1_4k6Jk560zf7P3Y_aZknLYg.png](attachment:6429a782-168a-4c7d-99db-65ec87658257.png)

**▪▶Important params**<br>
`dst`: array into which values are copied.<br>
`src`: array from which values are copied.


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Before arr1",arr1)
print("Before arr2",arr1)
np.copyto(arr1,arr2)
print("After arr1",arr1)
print("After arr2",arr2)

Before arr1 [1 2 3]
Before arr2 [1 2 3]
After arr1 [4 5 6]
After arr2 [4 5 6]


***

## Set Operations

### 31. Retrieve Common Elements
`np.intersect1d` function returns all the unique values from both arrays in a sorted manner.![1_IT4B7lKwo7lqNMLeDoJVDA.png](attachment:133c4059-1755-4c56-b0ff-e544c1de2bbd.png)

**▪▶Important params**<br>
`assume_unique`: if true, then input arrays are both assumed to be unique.<br>
`return_indices`: if true, then common elements indices are returned.

In [ ]:
ar1 = np.array([1,2,3,4,5,6])
ar2 = np.array([3,4,5,8,9,1])
np.intersect1d(ar1,ar2)

array([1, 3, 4, 5])

In [ ]:
np.intersect1d(ar1,ar2,return_indices=True)

(array([1, 3, 4, 5]), array([0, 2, 3, 4]), array([5, 0, 1, 2]))

```
array([0, 2, 3, 4], dtype=int64) :- Indices of common elements inside first array.
array([5, 0, 1, 2], dtype=int64)) :- Indices of common elements inside second array.
```

### 32. Difference
np.setdiff1d function returns all the unique elements from array 1 that are not present in arr2.

In [ ]:
a = np.array([1, 7, 3, 2, 4, 1])
b = np.array([9, 2, 5, 6, 7, 8])
np.setdiff1d(a, b)

array([1, 3, 4])

### 33. Extracts Unique Elements From Both Arrays
`setxor1d` function will return all the unique values from both arrays in sorted order.

In [ ]:
a = np.array([1, 2, 3, 4, 6])
b = np.array([1, 4, 9, 4, 36])
np.setxor1d(a,b)

array([ 2,  3,  6,  9, 36])

### 34. Union
union1d function will combine both arrays into one.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 3, 5, 4, 36])
np.union1d(a,b)

array([ 1,  2,  3,  4,  5, 36])

## Splitting
### 35. Horizontal Split
`hsplit` function will split the data horizontally into n equal parts.

In [ ]:
A = np.array([[3,4,5,2],[6,7,2,6]])
np.hsplit(A,2)    ## splits the data into two equal parts

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [ ]:
np.hsplit(A,4)    ## splits the data into four equal parts

[array([[3],
        [6]]),
 array([[4],
        [7]]),
 array([[5],
        [2]]),
 array([[2],
        [6]])]

### 36. Vertical Split
vsplit will split the data vertically into n equal parts.

In [ ]:
A = np.array([[3,4,5,2],[6,7,2,6]])
np.vsplit(A,2)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]

## Stacking

### 37. Horizontal Stacking
`hstack` will stack appends one array at the end of another.

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

### 38. Vertical Stacking
`vstack` will stack one array on top of another.

In [ ]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

## Comparing Two Arrays

### 39. allclose
`np.allclose` function finds whether two arrays are equal or approximately equal to each other based on some tolerance value if the shape of both arrays is the same.

In [ ]:
a = np.array([0.25,0.4,0.6,0.32])
b = np.array([0.26,0.3,0.7,0.32])
tolerance = 0.1           ## Total Difference
np.allclose(a,b,tolerance)

False

In [ ]:
tolerance = 0.5
np.allclose(a,b,tolerance)

True

### 40. Repeat
It is used to repeat elements of an array for n number of times.
![1_-P7D8NAOfMbQ5edIC6De2w.png](attachment:2dbb82c7-7cda-4930-a99e-553b343fa635.png)

**▪▶ Important params**<br>
`a`: element to repeat.<br>
`repeats`: number of times to repeat element.

In [ ]:
np.repeat('2017',3)

array(['2017', '2017', '2017'], dtype='<U4')

Let’s take a more practical use case example, we have a dataset containing year-wise container quantity sales.

In [ ]:
fruits = pd.DataFrame([
    ['Mango',40],
    ['Apple',90],
    ['Banana',130]
],columns=['Product','ContainerSales'])
fruits

Product  ContainerSales
0   Mango              40
1   Apple              90
2  Banana             130

In the dataset, the year column is missing. Let’s try to add it using numpy.

In [ ]:
fruits['year'] = np.repeat(2020,fruits.shape[0])
'''
Above code will repeat the year 2020 n times, where n is the length of data.
'''
fruits

Product  ContainerSales  year
0   Mango              40  2020
1   Apple              90  2020
2  Banana             130  2020

### 41. tile
Construct an array by repeating A the number of times given by reps.![1_pvZMA5HzqHU5oOkN-scEMg.png](attachment:e07624d3-9062-40d7-8f3c-a45f08def6cb.png)

In [ ]:
np.tile("Ram",5)

array(['Ram', 'Ram', 'Ram', 'Ram', 'Ram'], dtype='<U3')

In [ ]:
np.tile(3,(2,3))

array([[3, 3, 3],
       [3, 3, 3]])

## Einstein Summation Conventions

### 42. Einsum
This function is used to compute many multi-dimensional and linear algebraic operations on arrays.

In [ ]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(21,30).reshape(3,3)

## ▪️ᴇxᴛʀᴀᴄᴛꜱ ᴅɪᴀɢᴏɴᴀʟꜱ
np.einsum('ii->i',a)

array([1, 5, 9])

In [ ]:
## ▪️ᴛʀᴀɴꜱᴘᴏꜱᴇ
np.einsum('ji',a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
## ▪️ᴍᴀᴛʀɪx ᴍᴜʟᴛɪᴘɪᴄᴀᴛɪᴏɴ
np.einsum('ij,jk',a,b)

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

In [ ]:
##▪️ ꜱᴜᴍ ᴏꜰ ᴅɪᴀɢᴏɴᴀʟ
np.einsum('ii',a)

15

## Statistical Analysis

### 43. Histogram
It is an important statistical analysis function of NumPy that computes histogram values for a set of data.

In [ ]:
A = np.array([[3, 4, 5, 2],
              [6, 7, 2, 6]])
np.histogram(A)

(array([2, 0, 1, 0, 1, 0, 1, 0, 2, 1]),
 array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ]))

### 44. Percentile
It computes the q-th percentile of the data along a specified axis.![1_c1hFE8QMcZYSpLP413Ijwg.png](attachment:e58175f3-cef3-4d05-88b7-3b16cb030ca8.png)

**▪▶ Important params**<br>
`a`: array like input.<br>
`q`: percentile to compute.<br>
`overwrite_input`: if true, then allow the input array to modify the intermediate calculation to save memory.

In [ ]:
a = np.array([[2, 4, 6], [4, 8, 12]])
np.percentile(a, 50)

5.0

In [ ]:
np.percentile(a, 10)

3.0

In [ ]:
arr = np.array([2,3,4,1,6,7])
np.percentile(a,5)

2.5

### 45. Standard Deviation and Variance
std and var are two functions of NumPy that calculates standard deviation and variance along an axis.

In [ ]:
a = np.array([[2, 4, 6], [4, 8, 12]])

In [ ]:
np.std(a,axis=1)    ## Row Wise

array([1.63299316, 3.26598632])

In [ ]:
np.std(a,axis=0)    ## Column Wise

array([1., 2., 3.])

In [ ]:
np.var(a,axis=1)

array([ 2.66666667, 10.66666667])

In [ ]:
np.var(a,axis=0)

array([1., 4., 9.])

## Array Printing Options

### 46. Show Floats With Two Decimal Values

In [ ]:
np.set_printoptions(precision=2)
a = np.array([12.23456,32.34535])
print(a)

[12.23 32.35]


### 47. Prints Array To Its Max

In [ ]:
np.set_printoptions(threshold=np.inf)

### 48. Increase The Number of Elements In a Line

In [ ]:
np.set_printoptions(linewidth=100) ## Default 75

## Save and Load Array Data

### 49. Save
`savetxt` used to save the content of an array inside a text file.

In [ ]:
''' Generate array with 500 elements '''

arr = np.linspace(10,100,500).reshape(25,20)

##◾ 𝗦𝗮𝘃𝗲𝘀 𝗔𝗿𝗿𝗮𝘆 𝗗𝗮𝘁𝗮 𝗜𝗻𝘀𝗶𝗱𝗲 𝗮 𝘁𝘅𝘁 𝗙𝗶𝗹𝗲
np.savetxt('array.txt',arr)

### 50. Load
`loadtxt` used to load the content of an array from a text file. It takes the file name as a parameter.

In [ ]:
### ◾𝗟𝗼𝗮𝗱𝘀 𝗔𝗿𝗿𝗮𝘆 𝗗𝗮𝘁𝗮 𝗳𝗿𝗼𝗺 𝗮 𝘁𝘅𝘁 𝗙𝗶𝗹𝗲
np.loadtxt('array.txt')

array([[ 10.  ,  10.18,  10.36,  10.54,  10.72,  10.9 ,  11.08,  11.26,  11.44,  11.62,  11.8 ,
         11.98,  12.16,  12.34,  12.53,  12.71,  12.89,  13.07,  13.25,  13.43],
       [ 13.61,  13.79,  13.97,  14.15,  14.33,  14.51,  14.69,  14.87,  15.05,  15.23,  15.41,
         15.59,  15.77,  15.95,  16.13,  16.31,  16.49,  16.67,  16.85,  17.03],
       [ 17.21,  17.39,  17.58,  17.76,  17.94,  18.12,  18.3 ,  18.48,  18.66,  18.84,  19.02,
         19.2 ,  19.38,  19.56,  19.74,  19.92,  20.1 ,  20.28,  20.46,  20.64],
       [ 20.82,  21.  ,  21.18,  21.36,  21.54,  21.72,  21.9 ,  22.08,  22.26,  22.44,  22.63,
         22.81,  22.99,  23.17,  23.35,  23.53,  23.71,  23.89,  24.07,  24.25],
       [ 24.43,  24.61,  24.79,  24.97,  25.15,  25.33,  25.51,  25.69,  25.87,  26.05,  26.23,
         26.41,  26.59,  26.77,  26.95,  27.13,  27.31,  27.49,  27.68,  27.86],
       [ 28.04,  28.22,  28.4 ,  28.58,  28.76,  28.94,  29.12,  29.3 ,  29.48,  29.66,  29.84,
         30.02,  30

#51. empty
empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.



In [ ]:
np.empty([2, 2])

array([[4.96433176e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

#52. eye

eye returns a 2-D array with ones on the diagonal and zeros elsewhere. The main difference is that with the numpy. eye() the diagonal can may be offset, whereas numpy. identity() only fills the main diagonal.

#53. identity
    To return the identity array, use the numpy.identity()
    method in Python Numpy. The identity array is a square array with ones on the main diagonal.
    The 1s parameter is the number of rows (and columns) in n x n
    output. The function returns n x n array with its main diagonal set to one, and all other elements 0.

    The like parameter is a reference object to allow the creation of arrays which are not NumPy
    arrays. If an array-like passed in as like supports the __array_function__ protocol,
    the result will be defined by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

#54. Attributes of NumPy Array
    1.ndim
    2. shape
    3. size
    4. Datatype
    5. itemsize

#55. DataType in NumPy
    1. Boolean
    2. Float
    3. Integer
    4. Complex
    5. Unsigned Integer

#56.slicing and indexing
    indexing:
    syntax: arr_name[row_number,column_number]
    slicing:
    syntax: arr_name[depth_start_number:depth_stop_number:depth_step_number,row_start_number:row_stop_number:
    row_step_number,column_start_number:column_stop_number:column_step_number]


#56. Arithmetic Operation in NumPy Arrays
    1.+,
    2.-,
    3./,
    4.*,
    5./,
    6.//,
    7.%.
    using functions
    add,
    substract,
    multiply,
    divide,
    sqrt,
    
    


#57. Broadcasting NumPy
    Rulel: if the two arrays differ in their number of dimensions, the shape of the one with
    fewer dimension is padded with ones on its leading side(left side).
    Rule2: If the shape of the two arrays does not match in any dimension, the array with
    shape equal to I in that dimension is stretched to match the other shape.
    Rule 3: if in any dimension the sizes disagree and neither equal tol, an error is raised.

#58. Array Manipulation using NumPy
    1. reshaping
    2. array flatteing
        flatten and ravel
    3. dimension shuffling
        transpose and swapaxes
    4. joinig arrays
        Splitting and Joining
        vstack and hstack
    5. splitting arrays
        split, vsplit, hsplit
    6. add/remove elements to array.
        Insert, append,  Delete Function

#59. Matrix in NumPy
    1. dot
    2. Transpose



#60. Matrix Class in NumPy
    1. matrix
    2. addition
    3. multiplication
    4. Transpose


#61. Inverse Of A Matrix NumPy Linear Algebra
    1. numpy.linalg.inv()
    2. numpy.allclose(np.dot(a,b), np.eye(2))
    3. power
        np.linalg.matrix_power(a,2)
    4. determinent
    5. numpy.linalg.solve(a,b)




#62. ARRAYS WITH NUMERICAL RANGES
    ARANGE( ),
    LINSPACE( ),
    LOGSPACE( )

#63. INITIALIZING ARRAYS IN NUMPY
    ZEROS( ),
    ONES( ),
    FULL( ),
    EYE( ),
    shape( )
    reshape( )

#64. Indexing(Accessing) & Slicing

#65. UNDERSTANDING OF AXIS ATTRIBUTE IN NUMPY
        Axix=0---->Column
        Axis=1---->Row

#66. DATATYPES - COPY() - VIEW() IN NUMPY
    copy()
    view()
    i-int
    f-float
    S-string
    U-unicode string
    m-timedelta
    M-datatime
    O-Object
    V-void


#67. JOINING ARRAYS (CONCATENATE( ), STACK( ), VSTACK( ), HSTACK( ), DSTACK( )) IN NUMPY
        CONCATENATE( ),
        STACK( ),
        VSTACK( ),
        HSTACK( ),
        DSTACK( )

#68. SPLITTING ARRAY (SPLIT( ),ARRAY_SPLIT( ),VSPLIT( ),HSPLIT( )) IN NUMPY
        split(),
        Array_Split(),
        Vsplit(),
        Hsplit()
        

#SEARCH IN NUMPY (where( ) & searchsorted( ))
        Where(),
        Searchsorted()

#SORT( ) IN NUMPY - PYTHON PROGRAMMING
        sort()
        

#ARITHMETIC OPERATIONS ON ARRAYS IN NUMPY - PYTHON PROGRAMMING
        add()
        subtract()
        multilpy()
        real()
        img()
        conjugate()
        reciprocal()
        power()
        mod()

# STATISTICAL FUNCTIONS
    1. MIN
    2. MAX
    3. MEAN
    4. MEDIAN
    5. AVERAGE
    6. VARIANCE
    7. STANDARD DEVIATION

## Thanks For Reading
I hope You Found Someting useful.

### Don't Forgot to give the notebook a 🔼